services:
  mongo:
    image: mongo
    ports:
      - "27017:217"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PWD: qwerty
      